# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 323c95998b4b0fe3812ea19ad713245736dca1247f1895911e4e57545079a97474f4afa54deba4c99b570c8f93dd8161566b6244e97a997474d55fa50f368c00

test:
  secret_key_base: 9e8ef44049d406f74afb604c309cdc040bad9473660020d2ed50484f9e75b980219731685cd5bb509eac8eb24e00c73c3c61e02731cab500db63cdefa2b33224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
